/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.Cliente;
//import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import modelo.Empleado;
import modelo.Puesto;




/**
 *
 * @author WILMER
 */
public class fr_Persona extends javax.swing.JFrame {
Cliente cliente;
Empleado empleado;
Puesto puesto;

    //DefaultTableModel tblModelo;

    /**
     * Creates new form fr_Personas
     */
   public fr_Persona() {
        initComponents();
        cliente = new Cliente();
        empleado = new Empleado();
        puesto = new Puesto();
        
        this.tbl_clientes.setModel(cliente.leer());
        this.tbl_empleados.setModel(empleado.leerp());
        this.cbox_puesto.setModel(puesto.leer());
   }
        /*tblModelo = new DefaultTableModel();
        String encabezado [] = {"nit","nombres","apellidos","direccion","telefono","FechaNacimeinto"};
            tblModelo.setColumnIdentifiers(encabezado);
            tbl_clientes.setModel(tblModelo);
            
    }*/
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tab_principal = new javax.swing.JTabbedPane();
        panel_clientes = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_idt = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        lbl_nit = new javax.swing.JLabel();
        txt_nit = new javax.swing.JTextField();
        lbl_nombres = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JTextField();
        lbl_apellidos = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JTextField();
        lbl_direccion = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        lbl_telefono = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        lbl_nacimiento = new javax.swing.JLabel();
        txt_nacimiento = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jspanel_tabla = new javax.swing.JScrollPane();
        tbl_clientes = new javax.swing.JTable();
        panel_empleados = new javax.swing.JPanel();
        lbl_titulop = new javax.swing.JLabel();
        lbl_idtp = new javax.swing.JLabel();
        lbl_idp = new javax.swing.JLabel();
        lbl_codigop = new javax.swing.JLabel();
        txt_codigop = new javax.swing.JTextField();
        lbl_nombresp = new javax.swing.JLabel();
        txt_nombresp = new javax.swing.JTextField();
        lbl_apellidosp = new javax.swing.JLabel();
        txt_apellidosp = new javax.swing.JTextField();
        lbl_direccionp = new javax.swing.JLabel();
        txt_direccionp = new javax.swing.JTextField();
        lbl_telefonop = new javax.swing.JLabel();
        txt_telefonop = new javax.swing.JTextField();
        lbl_nacimientop = new javax.swing.JLabel();
        txt_nacimientop = new javax.swing.JTextField();
        btn_guardarp = new javax.swing.JButton();
        actualizarp = new javax.swing.JButton();
        btn_eliminarp = new javax.swing.JButton();
        jspanel_tablap = new javax.swing.JScrollPane();
        tbl_empleados = new javax.swing.JTable();
        lbl_puesto = new javax.swing.JLabel();
        cbox_puesto = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tab_principal.setBackground(new java.awt.Color(0, 0, 0));
        tab_principal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        tab_principal.setForeground(new java.awt.Color(255, 255, 255));

        panel_clientes.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N

        lbl_titulo.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lbl_titulo.setText("Formulario Clientes");

        lbl_idt.setText("ID:");

        lbl_id.setText("0");

        lbl_nit.setText("Nit:");

        txt_nit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_nit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nitActionPerformed(evt);
            }
        });

        lbl_nombres.setText("Nombres:");

        txt_nombres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_apellidos.setText("Apellidos:");

        txt_apellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_direccion.setText("Direccion:");

        txt_direccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_telefono.setText("Numero de telefono:");

        txt_telefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_nacimiento.setText("Fecha de nacimiento:");

        txt_nacimiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_guardar.setBackground(new java.awt.Color(0, 0, 255));
        btn_guardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        actualizar.setBackground(new java.awt.Color(51, 204, 255));
        actualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        actualizar.setForeground(new java.awt.Color(255, 255, 255));
        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        btn_eliminar.setBackground(new java.awt.Color(255, 51, 51));
        btn_eliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        tbl_clientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbl_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_clientes.setGridColor(new java.awt.Color(0, 0, 0));
        tbl_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_clientesMouseClicked(evt);
            }
        });
        tbl_clientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_clientesKeyReleased(evt);
            }
        });
        jspanel_tabla.setViewportView(tbl_clientes);

        javax.swing.GroupLayout panel_clientesLayout = new javax.swing.GroupLayout(panel_clientes);
        panel_clientes.setLayout(panel_clientesLayout);
        panel_clientesLayout.setHorizontalGroup(
            panel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_clientesLayout.createSequentialGroup()
                .addGroup(panel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_clientesLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(panel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_clientesLayout.createSequentialGroup()
                                .addGroup(panel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_nit)
                                    .addComponent(lbl_idt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_nombres))
                                .addGap(44, 44, 44)
                                .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_clientesLayout.createSequentialGroup()
                                .addGroup(panel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_nacimiento)
                                    .addGroup(panel_clientesLayout.createSequentialGroup()
                                        .addComponent(lbl_telefono)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addComponent(btn_guardar)
                                        .addGap(18, 18, 18)
                                        .addComponent(actualizar))
                                    .addGroup(panel_clientesLayout.createSequentialGroup()
                                        .addGroup(panel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_direccion)
                                            .addComponent(lbl_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(panel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_nit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txt_apellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                                .addComponent(txt_direccion, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                                .addComponent(txt_nombres)))))
                                .addGap(18, 18, 18)
                                .addComponent(btn_eliminar))))
                    .addGroup(panel_clientesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jspanel_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_clientesLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(lbl_titulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_clientesLayout.setVerticalGroup(
            panel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_clientesLayout.createSequentialGroup()
                .addComponent(lbl_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(panel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_id, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_idt))
                .addGap(9, 9, 9)
                .addGroup(panel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nit)
                    .addComponent(txt_nit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(panel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombres)
                    .addComponent(txt_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_apellidos)
                    .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_direccion)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_telefono)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_guardar)
                        .addComponent(actualizar)
                        .addComponent(btn_eliminar))
                    .addGroup(panel_clientesLayout.createSequentialGroup()
                        .addGroup(panel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nacimiento)
                            .addComponent(txt_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(jspanel_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99))
        );

        tab_principal.addTab("Clientes", panel_clientes);

        panel_empleados.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N

        lbl_titulop.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lbl_titulop.setText("Formulario Empleados");

        lbl_idtp.setText("ID:");

        lbl_idp.setText("0");

        lbl_codigop.setText("Codigo:");

        txt_codigop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_codigop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigopActionPerformed(evt);
            }
        });

        lbl_nombresp.setText("Nombres:");

        txt_nombresp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_apellidosp.setText("Apellidos:");

        txt_apellidosp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_direccionp.setText("Direccion:");

        txt_direccionp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_telefonop.setText("Numero de telefono:");

        txt_telefonop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_nacimientop.setText("Fecha de nacimiento:");

        txt_nacimientop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_guardarp.setBackground(new java.awt.Color(0, 0, 255));
        btn_guardarp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_guardarp.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardarp.setText("Guardar");
        btn_guardarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarpActionPerformed(evt);
            }
        });

        actualizarp.setBackground(new java.awt.Color(51, 204, 255));
        actualizarp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        actualizarp.setForeground(new java.awt.Color(255, 255, 255));
        actualizarp.setText("Actualizar");
        actualizarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarpActionPerformed(evt);
            }
        });

        btn_eliminarp.setBackground(new java.awt.Color(255, 51, 51));
        btn_eliminarp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_eliminarp.setText("Eliminar");
        btn_eliminarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarpActionPerformed(evt);
            }
        });

        tbl_empleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbl_empleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_empleados.setGridColor(new java.awt.Color(0, 0, 0));
        tbl_empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_empleadosMouseClicked(evt);
            }
        });
        tbl_empleados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_empleadosKeyReleased(evt);
            }
        });
        jspanel_tablap.setViewportView(tbl_empleados);

        lbl_puesto.setText("Puesto:");

        cbox_puesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbox_puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_puestoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_empleadosLayout = new javax.swing.GroupLayout(panel_empleados);
        panel_empleados.setLayout(panel_empleadosLayout);
        panel_empleadosLayout.setHorizontalGroup(
            panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_empleadosLayout.createSequentialGroup()
                .addGroup(panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_empleadosLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_empleadosLayout.createSequentialGroup()
                                .addGroup(panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_idtp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_nombresp))
                                .addGap(43, 43, 43)
                                .addComponent(lbl_idp, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_empleadosLayout.createSequentialGroup()
                                .addGroup(panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_nacimientop)
                                    .addGroup(panel_empleadosLayout.createSequentialGroup()
                                        .addGroup(panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panel_empleadosLayout.createSequentialGroup()
                                                .addComponent(lbl_telefonop)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txt_nacimientop, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_telefonop, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(panel_empleadosLayout.createSequentialGroup()
                                                .addGroup(panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbl_direccionp)
                                                    .addComponent(lbl_apellidosp, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lbl_codigop))
                                                .addGap(18, 18, 18)
                                                .addGroup(panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txt_apellidosp, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                                        .addComponent(txt_direccionp, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                                        .addComponent(txt_nombresp))
                                                    .addComponent(txt_codigop, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(23, 23, 23)
                                        .addGroup(panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panel_empleadosLayout.createSequentialGroup()
                                                .addComponent(btn_guardarp)
                                                .addGap(18, 18, 18)
                                                .addComponent(actualizarp))
                                            .addGroup(panel_empleadosLayout.createSequentialGroup()
                                                .addComponent(lbl_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbox_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)
                                .addComponent(btn_eliminarp))))
                    .addGroup(panel_empleadosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jspanel_tablap, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_empleadosLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(lbl_titulop)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panel_empleadosLayout.setVerticalGroup(
            panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_empleadosLayout.createSequentialGroup()
                .addGroup(panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_empleadosLayout.createSequentialGroup()
                        .addComponent(lbl_titulop)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_empleadosLayout.createSequentialGroup()
                        .addContainerGap(39, Short.MAX_VALUE)
                        .addGroup(panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_idtp)
                            .addComponent(lbl_idp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_codigop, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_codigop)
                            .addComponent(lbl_puesto)
                            .addComponent(cbox_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nombresp)
                    .addComponent(txt_nombresp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_apellidosp)
                    .addComponent(txt_apellidosp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_direccionp)
                    .addComponent(txt_direccionp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_telefonop)
                    .addComponent(txt_telefonop, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_guardarp)
                        .addComponent(actualizarp)
                        .addComponent(btn_eliminarp))
                    .addGroup(panel_empleadosLayout.createSequentialGroup()
                        .addGroup(panel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nacimientop)
                            .addComponent(txt_nacimientop, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(jspanel_tablap, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99))
        );

        tab_principal.addTab("Empleados", panel_empleados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_principal))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(tab_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        cliente = new Cliente(0,txt_nit.getText(),txt_nombres.getText(),txt_apellidos.getText(),txt_direccion.getText()
            ,txt_telefono.getText(),txt_nacimiento.getText());
        cliente.crear();
        tbl_clientes.setModel(cliente.leer());

        /* cliente.setNit(txt_nit.getText());
        cliente.setNombres(txt_nombres.getText());
        cliente.setApellidos(txt_apellidos.getText());
        cliente.setDireccion(txt_direccion.getText());
        cliente.setTelefono(txt_telefon.getText());
        cliente.setFecha_nacimiento(txt_nacimiento.getText());

        cliente.crear();
        tblModelo.addRow(cliente.crear());
        tbl_clientes.setModel(tblModelo);*/

    }//GEN-LAST:event_btn_guardarActionPerformed

    public void selec_datos(){
        int fila = tbl_clientes.getSelectedRow();
        lbl_id.setText(tbl_clientes.getValueAt(fila, 0).toString());
        txt_nit.setText(tbl_clientes.getValueAt(fila, 1).toString());
        txt_nombres.setText(tbl_clientes.getValueAt(fila, 2).toString());
        txt_apellidos.setText(tbl_clientes.getValueAt(fila, 3).toString());
        txt_direccion.setText(tbl_clientes.getValueAt(fila, 4).toString());
        txt_telefono.setText(tbl_clientes.getValueAt(fila, 5).toString());
        txt_nacimiento.setText(tbl_clientes.getValueAt(fila, 6).toString());
    }
    
    private void selec_datosp(){
        int fila = tbl_empleados.getSelectedRow();
        if (fila >= 0){
        lbl_idp.setText(tbl_empleados.getValueAt(fila, 0).toString());
        txt_codigop.setText(tbl_empleados.getValueAt(fila, 1).toString());
        txt_nombresp.setText(tbl_empleados.getValueAt(fila, 2).toString());
        txt_apellidosp.setText(tbl_empleados.getValueAt(fila, 3).toString());
        txt_direccionp.setText(tbl_empleados.getValueAt(fila, 4).toString());
        txt_telefonop.setText(tbl_empleados.getValueAt(fila, 5).toString());
        txt_nacimientop.setText(tbl_empleados.getValueAt(fila, 6).toString());
        String nompuesto = tbl_empleados.getValueAt(fila, 7) != null ? tbl_empleados.getValueAt(fila, 7).toString() : "";
        boolean encontrado = false;
        for(int i = 0; i < cbox_puesto.getItemCount(); i++){
            if(this.cbox_puesto.getItemAt(i).equals(nompuesto)){
                cbox_puesto.setSelectedIndex(i);
                encontrado = true;
                break;
            }
        }
        if(!encontrado){
            JOptionPane.showMessageDialog(null, "El puesto " + nompuesto + " fue encontrado..");
            cbox_puesto.setSelectedIndex(-1);
        }
        }
    }
    
    private void tbl_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_clientesMouseClicked
        // TODO add your handling code here:
        selec_datos();
    }//GEN-LAST:event_tbl_clientesMouseClicked

    private void tbl_clientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_clientesKeyReleased
        // TODO add your handling code here:
        selec_datos();
    }//GEN-LAST:event_tbl_clientesKeyReleased

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:
        cliente = new Cliente(Integer.parseInt(lbl_id.getText()),txt_nit.getText(),txt_nombres.getText(),txt_apellidos.getText(),txt_direccion.getText(),txt_telefono.getText(),txt_nacimiento.getText());
        cliente.actualizar();
        tbl_clientes.setModel(cliente.leer());
    }//GEN-LAST:event_actualizarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        cliente = new Cliente();
        cliente.setId(Integer.parseInt(lbl_id.getText()));
        cliente.eliminar();
        tbl_clientes.setModel(cliente.leer());
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void txt_nitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nitActionPerformed

    private void txt_codigopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigopActionPerformed

    private void btn_guardarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarpActionPerformed
        // TODO add your handling code here:
        String pseleccion = this.cbox_puesto.getSelectedItem().toString();
        Integer idseleccion = this.puesto.map.get(pseleccion);
        if(idseleccion != null){
            empleado = new Empleado (0, txt_codigop.getText(), txt_nombresp.getText(), txt_apellidosp.getText(),
                    txt_direccionp.getText(), txt_telefonop.getText(), txt_nacimientop.getText(),idseleccion.toString());
            empleado.crearp();
            tbl_empleados.setModel(empleado.leerp());
        }else{
            JOptionPane.showMessageDialog(null, "Error al guardar.." );
        }
    }//GEN-LAST:event_btn_guardarpActionPerformed

    private void tbl_empleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_empleadosMouseClicked
        // TODO add your handling code here:
        this.selec_datosp();
    }//GEN-LAST:event_tbl_empleadosMouseClicked

    private void tbl_empleadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_empleadosKeyReleased
        // TODO add your handling code here:
        this.selec_datosp();
    }//GEN-LAST:event_tbl_empleadosKeyReleased

    private void actualizarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarpActionPerformed
        // TODO add your handling code here:
        String pseleccionado = this.cbox_puesto.getSelectedItem().toString();
        Integer idseleccionado = puesto.map.get(pseleccionado);
        if(idseleccionado != null){
            empleado = new Empleado (Integer.parseInt(lbl_idp.getText()),txt_codigop.getText(),txt_nombresp.getText(),txt_apellidosp.getText(),txt_direccionp.getText(),txt_telefonop.getText(),
                txt_nacimientop.getText(),idseleccionado.toString());
            empleado.actualizarp();
            this.tbl_empleados.setModel(this.empleado.leerp());
        }else{
            JOptionPane.showMessageDialog(null, "Error al actualizar datos..");
        }
    }//GEN-LAST:event_actualizarpActionPerformed

    private void btn_eliminarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarpActionPerformed
        // TODO add your handling code here:
        empleado = new Empleado();
        empleado.setId(Integer.parseInt(this.lbl_idp.getText()));
        empleado.elimiarp();
        this.tbl_empleados.setModel(empleado.leerp());
    }//GEN-LAST:event_btn_eliminarpActionPerformed

    private void cbox_puestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_puestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_puestoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new fr_Persona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton actualizarp;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_eliminarp;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_guardarp;
    private javax.swing.JComboBox<String> cbox_puesto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jspanel_tabla;
    private javax.swing.JScrollPane jspanel_tablap;
    private javax.swing.JLabel lbl_apellidos;
    private javax.swing.JLabel lbl_apellidosp;
    private javax.swing.JLabel lbl_codigop;
    private javax.swing.JLabel lbl_direccion;
    private javax.swing.JLabel lbl_direccionp;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_idp;
    private javax.swing.JLabel lbl_idt;
    private javax.swing.JLabel lbl_idtp;
    private javax.swing.JLabel lbl_nacimiento;
    private javax.swing.JLabel lbl_nacimientop;
    private javax.swing.JLabel lbl_nit;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nombresp;
    private javax.swing.JLabel lbl_puesto;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JLabel lbl_telefonop;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_titulop;
    private javax.swing.JPanel panel_clientes;
    private javax.swing.JPanel panel_empleados;
    private javax.swing.JTabbedPane tab_principal;
    private javax.swing.JTable tbl_clientes;
    private javax.swing.JTable tbl_empleados;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_apellidosp;
    private javax.swing.JTextField txt_codigop;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_direccionp;
    private javax.swing.JTextField txt_nacimiento;
    private javax.swing.JTextField txt_nacimientop;
    private javax.swing.JTextField txt_nit;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JTextField txt_nombresp;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_telefonop;
    // End of variables declaration//GEN-END:variables
}
