/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import javax.swing.*;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Bomiki
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_ventana = new java.awt.TextArea();
        button_procesar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_ventana2 = new javax.swing.JLabel();
        longitud = new javax.swing.JLabel();
        total_palabras = new javax.swing.JLabel();
        letra_central = new javax.swing.JLabel();
        primera_letra = new javax.swing.JLabel();
        primera_palabra = new javax.swing.JLabel();
        ultima_letra2 = new javax.swing.JLabel();
        palabra_central = new javax.swing.JLabel();
        ultima_palabra = new javax.swing.JLabel();
        rep_a = new javax.swing.JLabel();
        rep_e = new javax.swing.JLabel();
        rep_i = new javax.swing.JLabel();
        rep_o = new javax.swing.JLabel();
        rep_u = new javax.swing.JLabel();
        palabras_par = new javax.swing.JLabel();
        palabras_impar = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_abrir = new javax.swing.JMenuItem();
        menu_guardar = new javax.swing.JMenuItem();
        menu_guardarcomo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menucopiar = new javax.swing.JMenuItem();
        menucortar = new javax.swing.JMenuItem();
        menupegar = new javax.swing.JMenuItem();
        menubuscar = new javax.swing.JMenuItem();
        menuremplazar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Manejo de cadenas");
        jLabel1.setToolTipText("");

        jLabel2.setText("Ingrese un texto o un archivo");

        button_procesar.setBackground(new java.awt.Color(153, 255, 153));
        button_procesar.setText("Procesar");
        button_procesar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        button_procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_procesarActionPerformed(evt);
            }
        });

        jLabel3.setText("Longitud del texto...");

        jLabel4.setText("Total de palabras...");

        jLabel5.setText("Primer letra del texto...");

        jLabel6.setText("Ultima letra del texto...");

        jLabel7.setText("letra central del texto...");

        jLabel8.setText("Primera palabra.....");

        jLabel9.setText("Palabra Central......");

        jLabel10.setText("Ultima palabra....");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Traduccion a clave murcielago");

        jLabel12.setText("Repeticiones de \"A\", \"a\" o \"a\".");

        jLabel13.setText("Repeticiones de \"E\", \"e\" o \"e\".");

        jLabel14.setText("Repeticiones de \"I\", \"i\" o \"i\"");

        jLabel15.setText("Repeticiones de \"O\",\"o\" o \"o\".");

        jLabel16.setText("Repeticiones de \"U\", \"u\" o \"u\".");

        jLabel17.setText("Palabras con cantidad de caracteres par.");

        jLabel18.setText("Palabras con cantidad de caracteres impar.");

        txt_ventana2.setBackground(new java.awt.Color(255, 255, 255));
        txt_ventana2.setForeground(new java.awt.Color(51, 51, 51));
        txt_ventana2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_ventana2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_ventana2.setOpaque(true);

        longitud.setBackground(new java.awt.Color(255, 255, 255));
        longitud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        longitud.setOpaque(true);

        total_palabras.setBackground(new java.awt.Color(255, 255, 255));
        total_palabras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        total_palabras.setOpaque(true);

        letra_central.setBackground(new java.awt.Color(255, 255, 255));
        letra_central.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        letra_central.setOpaque(true);

        primera_letra.setBackground(new java.awt.Color(255, 255, 255));
        primera_letra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        primera_letra.setOpaque(true);

        primera_palabra.setBackground(new java.awt.Color(255, 255, 255));
        primera_palabra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        primera_palabra.setOpaque(true);

        ultima_letra2.setBackground(new java.awt.Color(255, 255, 255));
        ultima_letra2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ultima_letra2.setOpaque(true);

        palabra_central.setBackground(new java.awt.Color(255, 255, 255));
        palabra_central.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        palabra_central.setOpaque(true);

        ultima_palabra.setBackground(new java.awt.Color(255, 255, 255));
        ultima_palabra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ultima_palabra.setOpaque(true);

        rep_a.setBackground(new java.awt.Color(255, 255, 255));
        rep_a.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rep_a.setOpaque(true);

        rep_e.setBackground(new java.awt.Color(255, 255, 255));
        rep_e.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rep_e.setOpaque(true);

        rep_i.setBackground(new java.awt.Color(255, 255, 255));
        rep_i.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rep_i.setOpaque(true);

        rep_o.setBackground(new java.awt.Color(255, 255, 255));
        rep_o.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rep_o.setOpaque(true);

        rep_u.setBackground(new java.awt.Color(255, 255, 255));
        rep_u.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rep_u.setOpaque(true);

        palabras_par.setBackground(new java.awt.Color(255, 255, 255));
        palabras_par.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        palabras_par.setOpaque(true);

        palabras_impar.setBackground(new java.awt.Color(255, 255, 255));
        palabras_impar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        palabras_impar.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(total_palabras, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(longitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(130, 130, 130)
                                        .addComponent(jLabel12)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(ultima_letra2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(primera_letra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(letra_central, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16))
                                    .addComponent(jLabel18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(button_procesar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17))))
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rep_a, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rep_e, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rep_i, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rep_o, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rep_u, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_ventana, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(primera_palabra, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(palabra_central, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                        .addComponent(ultima_palabra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(255, 255, 255)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(palabras_par, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(palabras_impar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_ventana2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(445, 445, 445))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1)))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ventana, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(button_procesar)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel12)
                        .addComponent(jLabel3)
                        .addComponent(longitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(rep_a, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel13))
                    .addComponent(total_palabras, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                    .addComponent(rep_e, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel14))
                    .addComponent(primera_letra, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                    .addComponent(rep_i, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel15))
                    .addComponent(ultima_letra2, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                    .addComponent(rep_o, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(letra_central, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                    .addComponent(rep_u, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel17))
                    .addComponent(primera_palabra, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                    .addComponent(palabras_par, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel18)
                    .addComponent(palabra_central, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                    .addComponent(palabras_impar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(ultima_palabra, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ventana2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Archivo");

        menu_abrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_abrir.setText("Abrir");
        menu_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_abrirActionPerformed(evt);
            }
        });
        jMenu1.add(menu_abrir);

        menu_guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_guardar.setText("Guardar");
        menu_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_guardarActionPerformed(evt);
            }
        });
        jMenu1.add(menu_guardar);

        menu_guardarcomo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_guardarcomo.setText("Guardar como");
        menu_guardarcomo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_guardarcomoActionPerformed(evt);
            }
        });
        jMenu1.add(menu_guardarcomo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        menucopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menucopiar.setText("Copiar");
        menucopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucopiarActionPerformed(evt);
            }
        });
        jMenu2.add(menucopiar);

        menucortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menucortar.setText("Cortar");
        menucortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucortarActionPerformed(evt);
            }
        });
        jMenu2.add(menucortar);

        menupegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menupegar.setText("Pegar");
        menupegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupegarActionPerformed(evt);
            }
        });
        jMenu2.add(menupegar);

        menubuscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menubuscar.setText("Buscar");
        menubuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubuscarActionPerformed(evt);
            }
        });
        jMenu2.add(menubuscar);

        menuremplazar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuremplazar.setText("Remplazar");
        menuremplazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuremplazarActionPerformed(evt);
            }
        });
        jMenu2.add(menuremplazar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_procesarActionPerformed
                                     
    String textoOriginal = txt_ventana.getText().toLowerCase().trim();
    int longitudTexto = textoOriginal.length();
    longitud.setText(String.valueOf(longitudTexto));
    String[][] traduccionMurcielago = {
        {"m", "0"}, {"u", "1"}, {"r", "2"}, {"c", "3"}, {"i", "4"}, {"e", "5"}, {"l", "6"}, {"a", "7"}, {"g", "8"}, {"o", "9"}
    };
    String textoTraducido = textoOriginal;
    for (String[] par : traduccionMurcielago) {
        textoTraducido = textoTraducido.replace(par[0], par[1]);
    }
    txt_ventana2.setText(textoTraducido);
    // System.out.println("Texto traducido: " + textoTraducido);
    // System.out.println("Longitud del texto original: " + longitudTexto);
    String[] palabras = textoOriginal.split("\\s+");
    int totalPalabras = palabras.length;
    total_palabras.setText(String.valueOf(totalPalabras));
    if (longitudTexto > 0) {
        String primeraLetra = String.valueOf(textoOriginal.charAt(0));
        primera_letra.setText(primeraLetra);
    }
    if (longitudTexto > 0) {
        String ultimaLetra = String.valueOf(textoOriginal.charAt(longitudTexto - 1));
        ultima_letra2.setText(ultimaLetra);
    }
    if (longitudTexto > 0) {
        int posicionCentral = longitudTexto / 2;
        String letraCentral = String.valueOf(textoOriginal.charAt(posicionCentral));
        letra_central.setText(letraCentral);
    }
    if (totalPalabras > 0) {
        primera_palabra.setText(palabras[0]);
    }
    if (totalPalabras > 0) {
        int posicionPalabraCentral = totalPalabras / 2;
        palabra_central.setText(palabras[posicionPalabraCentral]);
    }
    if (totalPalabras > 0) {
        ultima_palabra.setText(palabras[totalPalabras - 1]);
    }
    int repA = countOccurrences(textoOriginal, "a") + countOccurrences(textoOriginal, "á");
    int repE = countOccurrences(textoOriginal, "e") + countOccurrences(textoOriginal, "é");
    int repI = countOccurrences(textoOriginal, "i") + countOccurrences(textoOriginal, "í");
    int repO = countOccurrences(textoOriginal, "o") + countOccurrences(textoOriginal, "ó");
    int repU = countOccurrences(textoOriginal, "u") + countOccurrences(textoOriginal, "ú");
    rep_a.setText(String.valueOf(repA));
    rep_e.setText(String.valueOf(repE));
    rep_i.setText(String.valueOf(repI));
    rep_o.setText(String.valueOf(repO));
    rep_u.setText(String.valueOf(repU));
    StringBuilder palabrasPar = new StringBuilder();
    StringBuilder palabrasImpar = new StringBuilder();
    for (String palabra : palabras) {
        if (palabra.length() % 2 == 0) {
            palabrasPar.append(palabra).append(" ");
        } else {
            palabrasImpar.append(palabra).append(" ");
        }
    }
    palabras_par.setText(palabrasPar.toString().trim());
    palabras_impar.setText(palabrasImpar.toString().trim());
}
private int countOccurrences(String texto, String caracter) {
    int count = 0;
    int index = 0;
    while ((index = texto.indexOf(caracter, index)) != -1) {
        count++;
        index++;
    }
    return count;
    }//GEN-LAST:event_button_procesarActionPerformed

    private void menu_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_abrirActionPerformed
     JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Seleccionar un archivo de texto");
    fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos de texto (*.txt)", "txt"));
    int seleccion = fileChooser.showOpenDialog(this);
    if (seleccion == JFileChooser.APPROVE_OPTION) {
        File archivo = fileChooser.getSelectedFile();
        try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
            String linea;
            StringBuilder contenido = new StringBuilder();
            while ((linea = br.readLine()) != null) {
                contenido.append(linea).append("\n");
            }
           
            txt_ventana.setText(contenido.toString());

        } catch (IOException ex) {
            ex.printStackTrace();
        }
    } else {
        System.out.println("No se seleccionó ningún archivo.");
    }
    }//GEN-LAST:event_menu_abrirActionPerformed

    private void menu_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_guardarActionPerformed
        Object archivoActual = null;
       
        if (archivoActual != null) {
        
        try (BufferedWriter bw = new BufferedWriter(new FileWriter((String) archivoActual))) {
            bw.write(txt_ventana.getText());
            System.out.println("Archivo sobreescrito exitosamente.");
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    } else {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar archivo de texto");
        
        int seleccion = fileChooser.showSaveDialog(this);
        
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivoGuardar = fileChooser.getSelectedFile();
            if (!archivoGuardar.getName().toLowerCase().endsWith(".txt")) {
                archivoGuardar = new File(archivoGuardar.getAbsolutePath() + ".txt");
            }
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(archivoGuardar))) {
                bw.write(txt_ventana.getText());
                System.out.println("Archivo guardado exitosamente.");
                archivoActual = archivoGuardar;
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        } else {
            System.out.println("Operación de guardado cancelada.");
        }
    }
        
        
        
    }//GEN-LAST:event_menu_guardarActionPerformed

    private void menu_guardarcomoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_guardarcomoActionPerformed

        JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Guardar como");
    fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos de texto (*.txt)", "txt"));
    int seleccion = fileChooser.showSaveDialog(this);
    if (seleccion == JFileChooser.APPROVE_OPTION) {
        File archivoGuardar = fileChooser.getSelectedFile();
        if (!archivoGuardar.getName().toLowerCase().endsWith(".txt")) {
            archivoGuardar = new File(archivoGuardar.getAbsolutePath() + ".txt");
        }
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(archivoGuardar))) {
            bw.write(txt_ventana.getText());
            System.out.println("Archivo guardado exitosamente.");
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    } else {
        System.out.println("Operación de guardado cancelada.");
    }
    }//GEN-LAST:event_menu_guardarcomoActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void menupegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupegarActionPerformed

        Clipboard portapapeles = Toolkit.getDefaultToolkit().getSystemClipboard();
    try {
        Transferable contenido = portapapeles.getContents(null);
        if (contenido != null && contenido.isDataFlavorSupported(DataFlavor.stringFlavor)) {
            String textoPegado = (String) contenido.getTransferData(DataFlavor.stringFlavor);
            txt_ventana.insert(textoPegado, txt_ventana.getCaretPosition());
            System.out.println("Texto pegado: " + textoPegado);
        } else {
            System.out.println("No se encontrotexto en el portapapeles.");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
        
        
    }//GEN-LAST:event_menupegarActionPerformed

    private void menucopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucopiarActionPerformed

    String textoSeleccionado = txt_ventana.getSelectedText();
    if (textoSeleccionado != null && !textoSeleccionado.isEmpty()) {
        Clipboard portapapeles = Toolkit.getDefaultToolkit().getSystemClipboard();
        StringSelection seleccion = new StringSelection(textoSeleccionado);
        portapapeles.setContents(seleccion, null);
        System.out.println("Texto copiado en portapapeles: " + textoSeleccionado);
    } else {
        System.out.println("No se ha seleccionado ningún texto para copiar.");
    }
      
    }//GEN-LAST:event_menucopiarActionPerformed

    private void menuremplazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuremplazarActionPerformed

        String palabraBuscar = JOptionPane.showInputDialog(this, "Ingrese la palabra que desea reemplazar:");
    if (palabraBuscar != null && !palabraBuscar.isEmpty()) {
        String palabraReemplazar = JOptionPane.showInputDialog(this, "Ingrese la nueva palabra:");
        if (palabraReemplazar != null && !palabraReemplazar.isEmpty()) {
            String contenidoTexto = txt_ventana.getText();
            if (contenidoTexto.contains(palabraBuscar)) {
                String nuevoTexto = contenidoTexto.replace(palabraBuscar, palabraReemplazar);
                txt_ventana.setText(nuevoTexto);
                System.out.println("Se ha reemplazado \"" + palabraBuscar + "\" por \"" + palabraReemplazar + "\".");
            } else {
                JOptionPane.showMessageDialog(this, "La palabra \"" + palabraBuscar + "\" no fue encontrada.", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            System.out.println("Operación de reemplazo cancelada o palabra de reemplazo vacía.");
        }
    } else {
        System.out.println("Operación de búsqueda cancelada o palabra de búsqueda vacía.");
        
    }
    }//GEN-LAST:event_menuremplazarActionPerformed

    private void menubuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubuscarActionPerformed

        String palabra = JOptionPane.showInputDialog(this, "Ingrese la palabra a buscar:");
    if (palabra != null && !palabra.isEmpty()) {
        String contenidoTexto = txt_ventana.getText();
        int posicion = contenidoTexto.indexOf(palabra);
        if (posicion >= 0) {
            txt_ventana.setCaretPosition(posicion);
            txt_ventana.select(posicion, posicion + palabra.length());
            txt_ventana.requestFocusInWindow();
            System.out.println("Palabra encontrada en la posición: " + posicion);
        } else {
            JOptionPane.showMessageDialog(this, "Palabra no encontrada.", "Resultado", JOptionPane.INFORMATION_MESSAGE);
        }
    } else {
        System.out.println("Búsqueda cancelada o palabra vacía.");
    }
        
        
    }//GEN-LAST:event_menubuscarActionPerformed

    private void menucortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucortarActionPerformed

        String textoSeleccionado = txt_ventana.getSelectedText();

    if (textoSeleccionado != null && !textoSeleccionado.isEmpty()) {
        Clipboard portapapeles = Toolkit.getDefaultToolkit().getSystemClipboard();
        StringSelection seleccion = new StringSelection(textoSeleccionado);
        portapapeles.setContents(seleccion, null);
        this.txt_ventana.setText("");
        System.out.println("Texto cortado al portapapeles: " + textoSeleccionado);
    } else {
        System.out.println("No se ha seleccionado ningún texto para cortar.");
    }
    }//GEN-LAST:event_menucortarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_procesar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel letra_central;
    private javax.swing.JLabel longitud;
    private javax.swing.JMenuItem menu_abrir;
    private javax.swing.JMenuItem menu_guardar;
    private javax.swing.JMenuItem menu_guardarcomo;
    private javax.swing.JMenuItem menubuscar;
    private javax.swing.JMenuItem menucopiar;
    private javax.swing.JMenuItem menucortar;
    private javax.swing.JMenuItem menupegar;
    private javax.swing.JMenuItem menuremplazar;
    private javax.swing.JLabel palabra_central;
    private javax.swing.JLabel palabras_impar;
    private javax.swing.JLabel palabras_par;
    private javax.swing.JLabel primera_letra;
    private javax.swing.JLabel primera_palabra;
    private javax.swing.JLabel rep_a;
    private javax.swing.JLabel rep_e;
    private javax.swing.JLabel rep_i;
    private javax.swing.JLabel rep_o;
    private javax.swing.JLabel rep_u;
    private javax.swing.JLabel total_palabras;
    private java.awt.TextArea txt_ventana;
    private javax.swing.JLabel txt_ventana2;
    private javax.swing.JLabel ultima_letra2;
    private javax.swing.JLabel ultima_palabra;
    // End of variables declaration//GEN-END:variables
}
