/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.*;

/**
 *
 * @author WILMER
 */
public class pr_persona extends javax.swing.JFrame {
    docente Docente;
    persona Persona;
     

    /**
     * Creates new form pr_persona
     */
    public pr_persona() {
        initComponents();
        Persona = new persona();
        tbl_docente.setModel(Persona.leerp());
        ocultarColumnas();
    }

    
    
     private void ocultarColumnas() {
    tbl_docente.getColumnModel().getColumn(10).setMinWidth(0);
    tbl_docente.getColumnModel().getColumn(10).setMaxWidth(0);
    tbl_docente.getColumnModel().getColumn(10).setWidth(0);
    tbl_docente.getColumnModel().getColumn(10).setPreferredWidth(0);

    tbl_docente.getColumnModel().getColumn(11).setMinWidth(0);
    tbl_docente.getColumnModel().getColumn(11).setMaxWidth(0);
    tbl_docente.getColumnModel().getColumn(11).setWidth(0);
    tbl_docente.getColumnModel().getColumn(11).setPreferredWidth(0);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnl_docente = new javax.swing.JPanel();
        lbl_principal = new javax.swing.JLabel();
        lbl_nit = new javax.swing.JLabel();
        txt__nit = new javax.swing.JTextField();
        lbl_nombres = new javax.swing.JLabel();
        txt__nombres = new javax.swing.JTextField();
        lbl_apellidos = new javax.swing.JLabel();
        txt__apellidos = new javax.swing.JTextField();
        lbl_direccion = new javax.swing.JLabel();
        txt__direccion = new javax.swing.JTextField();
        lbl_telefono = new javax.swing.JLabel();
        txt__telefono = new javax.swing.JTextField();
        fecha_nacimiento = new javax.swing.JLabel();
        txt__fecha_nacimiento = new javax.swing.JTextField();
        lbl_codigo_docente = new javax.swing.JLabel();
        txt__codigo_docente = new javax.swing.JTextField();
        lbl_salario = new javax.swing.JLabel();
        txt__salario = new javax.swing.JTextField();
        lbl_fecha_ingreso = new javax.swing.JLabel();
        fecha_ingreso = new javax.swing.JTextField();
        lbl_fecha_registro = new javax.swing.JLabel();
        fecha_registro = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_docente = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_principal.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lbl_principal.setText("Formulario Docente");

        lbl_nit.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lbl_nit.setText("Nit:");

        txt__nit.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txt__nit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt__nitActionPerformed(evt);
            }
        });

        lbl_nombres.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lbl_nombres.setText("Nombres:");

        txt__nombres.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        lbl_apellidos.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lbl_apellidos.setText("Apelldios:");

        txt__apellidos.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        lbl_direccion.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lbl_direccion.setText("Direccion:");

        txt__direccion.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        lbl_telefono.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lbl_telefono.setText("Telefono:");

        txt__telefono.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        fecha_nacimiento.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        fecha_nacimiento.setText("Fecha de Nacimiento:");

        txt__fecha_nacimiento.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        lbl_codigo_docente.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lbl_codigo_docente.setText("Codigo docente:");

        txt__codigo_docente.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        lbl_salario.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lbl_salario.setText("Salario:");

        txt__salario.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        lbl_fecha_ingreso.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lbl_fecha_ingreso.setText("Fecha Ingreso laboral:");

        fecha_ingreso.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        lbl_fecha_registro.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lbl_fecha_registro.setText("Fecha registro de ingreso:");

        fecha_registro.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        btn_guardar.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_actualizar.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        btn_actualizar.setText("Actualizar");

        btn_eliminar.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        btn_eliminar.setText("Eliminar");

        tbl_docente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_docente);

        javax.swing.GroupLayout pnl_docenteLayout = new javax.swing.GroupLayout(pnl_docente);
        pnl_docente.setLayout(pnl_docenteLayout);
        pnl_docenteLayout.setHorizontalGroup(
            pnl_docenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_docenteLayout.createSequentialGroup()
                .addGroup(pnl_docenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_docenteLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(pnl_docenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_docenteLayout.createSequentialGroup()
                                .addComponent(fecha_nacimiento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt__fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_docenteLayout.createSequentialGroup()
                                .addGroup(pnl_docenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_docenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbl_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_telefono)
                                    .addComponent(lbl_nit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_docenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt__nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt__nit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt__apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt__direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt__telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29)
                        .addGroup(pnl_docenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_docenteLayout.createSequentialGroup()
                                .addGroup(pnl_docenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_codigo_docente)
                                    .addComponent(lbl_salario))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnl_docenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt__codigo_docente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt__salario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnl_docenteLayout.createSequentialGroup()
                                .addGroup(pnl_docenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_fecha_registro)
                                    .addComponent(lbl_fecha_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_docenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fecha_registro, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(fecha_ingreso)))))
                    .addGroup(pnl_docenteLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btn_guardar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_actualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar))
                    .addGroup(pnl_docenteLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(lbl_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_docenteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnl_docenteLayout.setVerticalGroup(
            pnl_docenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_docenteLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbl_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_docenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_nit)
                    .addComponent(txt__nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_docenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombres)
                    .addComponent(txt__nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_docenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_apellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_codigo_docente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt__apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt__codigo_docente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_docenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_direccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_salario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt__direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt__salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_docenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_fecha_ingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt__telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_docenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha_nacimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_docenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_fecha_registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt__fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fecha_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnl_docenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(btn_actualizar)
                    .addComponent(btn_eliminar))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_docente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_docente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt__nitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt__nitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt__nitActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pr_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pr_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pr_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pr_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pr_persona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JTextField fecha_ingreso;
    private javax.swing.JLabel fecha_nacimiento;
    private javax.swing.JTextField fecha_registro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_apellidos;
    private javax.swing.JLabel lbl_codigo_docente;
    private javax.swing.JLabel lbl_direccion;
    private javax.swing.JLabel lbl_fecha_ingreso;
    private javax.swing.JLabel lbl_fecha_registro;
    private javax.swing.JLabel lbl_nit;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_principal;
    private javax.swing.JLabel lbl_salario;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JPanel pnl_docente;
    private javax.swing.JTable tbl_docente;
    private javax.swing.JTextField txt__apellidos;
    private javax.swing.JTextField txt__codigo_docente;
    private javax.swing.JTextField txt__direccion;
    private javax.swing.JTextField txt__fecha_nacimiento;
    private javax.swing.JTextField txt__nit;
    private javax.swing.JTextField txt__nombres;
    private javax.swing.JTextField txt__salario;
    private javax.swing.JTextField txt__telefono;
    // End of variables declaration//GEN-END:variables
}
